#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : thunderbolt-software-user-space
Version  : 0.9.2
Release  : 6
URL      : https://github.com/01org/thunderbolt-software-user-space/archive/v0.9.2.tar.gz
Source0  : https://github.com/01org/thunderbolt-software-user-space/archive/v0.9.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: thunderbolt-software-user-space-bin
Requires: thunderbolt-software-user-space-config
Requires: thunderbolt-software-user-space-data
BuildRequires : boost-dev
BuildRequires : cmake
BuildRequires : pkgconfig(udev)
Patch1: build.patch

%description
# Thunderbolt(TM) user-space components
## License
These components are distributed under a BSD-style license. See COPYING for the
full license.

%package bin
Summary: bin components for the thunderbolt-software-user-space package.
Group: Binaries
Requires: thunderbolt-software-user-space-data
Requires: thunderbolt-software-user-space-config

%description bin
bin components for the thunderbolt-software-user-space package.


%package config
Summary: config components for the thunderbolt-software-user-space package.
Group: Default

%description config
config components for the thunderbolt-software-user-space package.


%package data
Summary: data components for the thunderbolt-software-user-space package.
Group: Data

%description data
data components for the thunderbolt-software-user-space package.


%prep
%setup -q -n thunderbolt-software-user-space-0.9.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506612212
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1506612212
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/udev/tbtacl
/usr/lib/udev/tbtacl-write

%files bin
%defattr(-,root,root,-)
/usr/bin/tbtadm

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/60-tbtacl.rules

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/tbtadm
/usr/share/doc/thunderbolt-user-space/copyright
